SET DEFINE OFF

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (70, 'SHF Sheriff');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (11, 'PPD Police');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (13, 'PFD Fire');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (84, 'FJD 1st Judicial District PA');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (36, 'REV Revenue');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (16, 'PPR Parks and Recreation');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (42, 'COM Commerce');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (4, 'OIT Ofc of Innovation and Tech');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (12, 'STS Streets');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (23, 'PPS Prisons');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (10, 'MDO Managing Director Office');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (28, 'PWD Water');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (59, 'OPA Ofc of Property Assessment');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (27, 'LRB L and I Review Board');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (22, 'DHS Dept of Human Services');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (92, 'PHL Dept of Aviation');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (14, 'DPH Health');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (68, 'ROW Register of Wills');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (1, 'PCC City Council');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (5, 'MAY Mayor');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (52, 'FLP Free Library of Phila');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (65, 'CAO Ofc of Chief Admin Officer');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (24, 'OSH Ofc of Homeless Services');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (15, 'DBH Behav Hlth ID Svcs');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (35, 'FIN Finance');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (49, 'MOS Office of Sustainability');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (8, 'CEO Community Empowerment Ofc');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (69, 'DAO District Attorney');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (44, 'LAW Law Dept');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (53, 'BPR Board of Pensions Retiremt');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (73, 'CMS City Commissioners');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (50, 'MAP Mural Arts Program');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (25, 'OFM Fleet Management');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (56, 'OHR Office of Human Resources');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (20, 'DPP Public Property');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (63, 'BRT Board of Revision of Taxes');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (26, 'LNI Licenses and Inspections');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (54, 'CHR Phila Comsn on Hum Relatns');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (31, 'REC Records');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (3, 'OLR Office of Labor');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (61, 'CLR City Controller');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (38, 'PRO Procurement');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (72, 'DPD Planning and Development');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (41, 'REP City Representative');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (58, 'OAC Ofc Arts Culture Creativ E');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (48, 'OIG Ofc of Inspector General');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (66, 'MOE Mayors Office of Education');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (40, 'CTO City Treasurer');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (45, 'BOE Board of Ethics');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (51, 'CPC City Planning Commission');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (55, 'CSC Civil Service Commission');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) 
VALUES (29, 'BBS Board of Buildng Standards');

